server:
  port: 8081



spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bpj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
logging:
  file:
    name: log
  level:
    log: info